### ISSUE TITLE
bug on ipad iOS 8.0.2

### ISSUE THREAD

**Issue by dannywng** [imsky/holder#116]
when I run Holder.run(), my iPad will reports error on line367 ( s = new n.Text(p.text);). it says TypeError: Attempted to assign to readonly property. And then holder fails to render.

**Comment by imsky** [comment]
This is now fixed. The problem was due to a Safari 8 bug covered in more detail here:
* https://github.com/emberjs/ember.js/pull/5629
* http://stackoverflow.com/questions/25174594/typeerror-attempted-to-assign-to-readonly-property-on-ios8-safari
