### ISSUE TITLE
100% doesn't work on single page more than once with bootstrap 3.2.0

### ISSUE THREAD

**Issue by osricmacon** [imsky/holder#122]
100% doesn't work on single page more than once with bootstrap 3.2.0

**Comment by imsky** [comment]
With a minimal test case like the codepen you provided, I could not replicate this issue:

```html
<!doctype html>
<html>
<body>
<div style="height:200px">
  <img src="holder.js/100%x100%/lava">
  <img src="holder.js/100%x200/sky">
</div>
<script src="../holder.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>
```

Let me know if this bug still occurs for you. I'm closing the issue in the meantime.

**Comment by osricmacon** [comment]
It does occurs for me but i am not able to replicate on codepen so it is my own problem not a bug of holderjs. Good that you closed this. I assumed it's closed long back.
:)

**Comment by imsky** [comment]
@osricmacon Feel free to email me the page where you're seeing the bug.
