### ISSUE TITLE
SVG Visibility Problem

### ISSUE THREAD

**Issue by Gavin-Paolucci-Kleinow** [imsky/holder#127]
I've hit a problem with using holder.js. It occurs when the placeholder image is larger than the window size but is sized down through CSS to fit the within the window. Because the SVG element that creates the placeholder images is set to visibility: hidden, that element will take up height and width and force scrollbars. [Here's a jsfiddle example](http://jsfiddle.net/Gavin_Paolucci_Kleinow/3sac8LL1/1/).

This is especially a problem with me in angular.js where the SVG gets added to the end of the body element and persists between views.

**Comment by imsky** [comment]
Thanks for reporting this, it definitely needs a fix. I'll add it to 2.5.

**Comment by Gavin-Paolucci-Kleinow** [comment]
Sure. Thanks for fixing it so quickly!

**Comment by imsky** [comment]
Sure thing, let me know if you encounter the bug in the future.
