### ISSUE TITLE
Meteor package does not exist

### ISSUE THREAD

**Issue by PulsarBlow** [imsky/holder#132]
According to the readme.md one can install Holder as a meteor package with the following command :

```meteor add holder```

This package does not exist on Atmosphere.

```error: no such package```

Is the offical Holder Meteor package is? :

```meteor add pcel:holder```

**Comment by imsky** [comment]
Thanks for letting me know. Use either pcel's or dsyko's package in the meantime.

**Comment by imsky** [comment]
There is now an official `imsky:holder` package.

**Comment by PulsarBlow** [comment]
Thanks you

**Comment by imsky** [comment]
You're welcome, glad to get it resolved.
