### ISSUE TITLE
Joomla subfolders Not Work

### ISSUE THREAD

**Issue by leoalv** [imsky/holder#133]
I've been testing in Joomla and does not work.

I started using sample file, but the simple fact of placing slash "/" at the beginning no longer works.

Full text of Joomla can be used with DATA-SRC, but not with SRC. And if we try to use images fields joomla, much worse.

Any idea or solution to this ?.

great work

**Comment by imsky** [comment]
If using `data-src` works, please use that. If you'd like to only use `src`, please provide a live URL of the breaking page.

**Comment by imsky** [comment]
Closing this due to no response. If the bug is available to review live, please post the relevant URL.
