### ISSUE TITLE
some bugs on old platform

### ISSUE THREAD

**Issue by oonxt** [imsky/holder#134]
line 320/333:
callback(global.performance.now());    

global.performance is not defined. 
callback(Date.now()) works fine.

line 325/338:
global.cancelAnimationFrame = webkitCancelAnimationFrame; 
webkitCancelAnimationFrame is not defined

global.cancelAnimationFrame = window.webkitCancelAnimationFrame works too.

**Comment by imsky** [comment]
thanks, I'll look into it

**Comment by kaluznyo** [comment]
On older android default browser, webkitCancelAnimationFrame is not defined is still there

**Comment by kaluznyo** [comment]
global.cancelAnimationFrame = window.webkitCancelAnimationFrame; at line 224 seems work

**Comment by imsky** [comment]
thanks @kaluznyo i'll take another look - had a related bug report this week

**Comment by jtammen** [comment]
@imsky I am also seeing this in my error logs … any chance you can take a look at it? Thanks! (-:

**Comment by imsky** [comment]
ok will take another look

**Comment by imsky** [comment]
fix has been pushed to 2.9.1. let me know if you encounter this issue again
