### ISSUE TITLE
Font size flag not working

### ISSUE THREAD

**Issue by funtoosh** [imsky/holder#135]
Hey there,
can't get the size flag to work, am I missing sth. here? Oh wait, could this be a browser issue? Tried <img data-src="holder.js/300x200/size:40"> on FF 31.6.0 (ESR) … the font size remains at default though.
Otherwise, this is way beautiful .-)
Cheers,
-f

**Comment by imsky** [comment]
I've just tested the size flag in the latest ESR, it appears to be working. Please post a live example.

![size_flag_esr](https://cloud.githubusercontent.com/assets/330895/7045707/82d77052-ddce-11e4-867f-46b1541fa736.png)

**Comment by funtoosh** [comment]
Ivan, you are right, of course, no problem at all in the jsfiddle. 
Earlier, I was using the version of holder.js that came bundled w/ bootstrap (2.4.1+f2l1h), so I suppose it's down to that slightly oldish version …

![bild 898](https://cloud.githubusercontent.com/assets/506433/7046307/0485e0c6-de05-11e4-84f5-5377798f8570.png)

**Comment by funtoosh** [comment]
Oops, a PS: I can't make the size flag work with aforementioned v2.4.1+f2l1h, nor with the latest v2.6.0, but v2.5.2+2mg3u works like a charm ...

Cheers, -f

**Comment by imsky** [comment]
The example still works with 2.6.0: http://jsfiddle.net/9vuvxfkn/17/

**Comment by funtoosh** [comment]
Wow, now that's weird! 
Your version works, but look at these two:

![bild 900](https://cloud.githubusercontent.com/assets/506433/7047250/a8752e2a-de0b-11e4-8fda-55d17629253c.png)

![bild 901](https://cloud.githubusercontent.com/assets/506433/7047251/a87919b8-de0b-11e4-81ec-b8de4c54070c.png)

**Comment by funtoosh** [comment]
Autsch, my fault, i was using an incomplete holder.js with dependencies to libs and utils! 
Very sorry!

**Comment by imsky** [comment]
No problem, glad your issue was resolved.
