### ISSUE TITLE
Unit test fails with PhantomJS

### ISSUE THREAD

**Issue by tomohiro-n** [imsky/holder#137]
Hi,

I'm using holder.js v2.6.0 and ran into sort of reasonably incompatible error with PhantomJS at my unit testing as below.

```
PhantomJS 1.9.8 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating 'global.requestAnimationFrame(visibilityCheck)')
  at /blah/blah/blah/bower_components/holderjs/holder.js:1003
```

I understand holder.js doesn't have to work with no-UI environment but it's appreciated if we could avoid an error by not evaluating it on PhantomJS or so.
The workaround I did was to add [requestAnimationFrame](https://github.com/cagosta/requestAnimationFrame) to devDependencies and unbeautifully manipulated an order them to be read at testing.

Thank you!

**Comment by imsky** [comment]
Thanks for reporting this, I'll look into it.
