### ISSUE TITLE
Bugfix after ajax page reload

### ISSUE THREAD

**Issue by zazoley** [imsky/holder#141]
Original piece of code:

//Remove CSS
while (style.childNodes.length) {
	style.removeChild(style.childNodes[0]);
}

gives an error "Uncaught TypeError: Cannot read property 'childNodes' of null" when I reload piece of page via ajax.

Possible fix that solve the problem:

//Remove CSS
if (style) {
    while (style.childNodes.length) {
        style.removeChild(style.childNodes[0]);
    }
}

**Comment by imsky** [comment]
I'll look into it.

**Comment by imsky** [comment]
This should be fixed in 2.8. If you keep seeing this bug please post a link to a test case.
