### ISSUE TITLE
The "auto" function does not work in ie 8

### ISSUE THREAD

**Issue by endichen** [imsky/holder#146]
first, there is 
"<" img id="previewImg" data-src="holder.js/300x300/auto" ">"
then, change the src of "previewImg", and the height of src img is less than 300,(such as 300 * 200)
but the size of  "previewImg" is still 300 * 300.

in firefox and chrome, it works fine( the size of "previewImg" can auto change). 
but in ie 8 ,it does not work.
please help,thanks!

**Comment by imsky** [comment]
Thanks for reporting this. I can replicate the bug in IE8 and latest Chrome. Please report your version, since "holder.js/300x300/auto" is pre-2.8 syntax.

**Comment by imsky** [comment]
This is by design: https://github.com/imsky/holder/blob/master/src/lib/holder.js#L467

Auto-sized HTML placeholders (the kind IE8 renders) collapse to 0x0 dimensions without an explicit width and height.

To fix this, before you change the src, set the width/height properties to `auto`/`initial`.

**Comment by endichen** [comment]
I have try this : 
$("#previewImg").style.width = 300;
$("#previewImg").style.height = 200; 
and  this:
$("#previewImg").style.width = "auto/initial";
$("#previewImg").style.height = "auto/initial";
before I change the src.
But it still does not work.
What do you mean "set the width/height properties to auto/initial" ?

**Comment by imsky** [comment]
Try doing this instead:
```js
$('#previewImg').css({'width': 'auto', 'height': 'auto'});
```

**Comment by endichen** [comment]
Good, It works fine! Thanks!

**Comment by imsky** [comment]
Great to hear it works.
