### ISSUE TITLE
Error with cdnjs and jsDeliver

### ISSUE THREAD

**Issue by fpoirier1** [imsky/holder#147]
I get an error message when loading Holder.js from cdnjs and jsDeliver but it works fine with RawGit.

**Comment by fpoirier1** [comment]
http://codepen.io/fpoirier1/pen/VLbKBY

**Comment by jimaek** [comment]
http://www.jsdelivr.com/#!holder is the website, the actual file is `https://cdn.jsdelivr.net/holder/2.8.0/holder.min.js`

**Comment by imsky** [comment]
Here is the Codepen, updated with the correct JS source and `src` syntax:
http://codepen.io/anon/pen/doWOWO
