### ISSUE TITLE
How about to display text and size together??

### ISSUE THREAD

**Issue by yPangXie** [imsky/holder#148]
I have some conditions to notify my user that this image means "product image" and its size is "200x200", so I am thingking about if there is a way to show up the text and size together?

Currently I can do it with codes `<img data-src="holder.js/200x200?text=Product Image(200x200)" />`, is it possible to show up them(like attribute alt) with some settings since I have to type the size manually which might make some mistakes(like typing 200x299 instead of 200x200 by my fault)??

Thanks.

**Comment by yPangXie** [comment]
Forked this repo and made some updates here [https://github.com/yPangXie/holder/commit/bf08a31dc11e57c838525a656160436364099a72](https://github.com/yPangXie/holder/commit/bf08a31dc11e57c838525a656160436364099a72)

**Comment by imsky** [comment]
It's probably best to make this feature more generic, i.e. add the ability to put the dimensions of the placeholder anywhere within the text. I'll look into implementing it.

**Comment by yPangXie** [comment]
Awesome!
