### ISSUE TITLE
100% CPU usage on Google Chrome

### ISSUE THREAD

**Issue by anka-213** [imsky/holder#149]
Every site that has holder.js loaded uses 100% CPU for me as long as I have it open. The Chrome Development Tools profiler says that `(program)` is the culprit, so there's not much help from that.

I also tried resetting Google Chrome to see if it was a problem with some extension, but it didn't help.

System info:
Browser: Google Chrome Version 43.0.2357.132 m
OS: Windows 10 Pro Insider Preview

**Comment by anka-213** [comment]
This is sufficient to replicate the bug:

````
<html>
<head><script src="https://cdn.rawgit.com/imsky/holder/master/holder.js"></script></head>
<body>Hello</body>
</html>
````

**Comment by imsky** [comment]
What OS? Have you looked at the Activity Monitor in OS X or Task Manager in Windows or Ubuntu? CPU usage goes to 100% while profiling - are you sure it's Holder-related and that it can't be replicated with any other library?

**Comment by anka-213** [comment]
A git bisect using the html-file above and running gulp between each iteration tells me that the issue was introduced in commit 41c9258.

**Comment by imsky** [comment]
That seems unlikely. Can you replicate the issue in a different browser and answer my previous questions?

**Comment by anka-213** [comment]
I said Windows 10 in the bottom of my post.
No, I haven't found any other library that causes the issue. I discovered it on the getbootstrap.com website and pinpointed it to holder by removing js code until the issue disappeared. And since just including the library on a webpage is sufficient I concluded that this was causing it.

**Comment by anka-213** [comment]
No I can't replicate it in another browser.

**Comment by anka-213** [comment]
I agree that it seems unlikely that the commit I mentioned is the cause, but it became visible after that commit.

I guess it's some kind of bug in Google Chrome, but it is being triggered by your library.

**Comment by anka-213** [comment]
(And no, I only started the profiling after I discovered that the webpage was using 100% cpu, so that is not the cause)

**Comment by anka-213** [comment]
@imsky More specifically, I believe that the line: `global.requestAnimationFrame(visibilityCheck);` is the culprit. It seems likely since the 100% cpu usage is only an issue when the page is visible. If it is in a background tab, it is using normal amounts of cpu.

**Comment by anka-213** [comment]
http://stackoverflow.com/questions/28390358/high-cpu-usage-with-canvas-and-requestanimationframe

**Comment by imsky** [comment]
OK can you replicate it with just `requestAnimationFrame`? If it's a problem with rAF it's a Chrome bug and should be filed there.

**Comment by anka-213** [comment]
Yes, it seems so. The example (http://www.duckware.com/test/chrome/requestanimationframe.html) on https://code.google.com/p/chromium/issues/detail?id=321632 gives the same result. Thanks for the help.

**Comment by anka-213** [comment]
Although I'm not entirely sure that the way you are using the function is correct. You are essentially polling for visibility on every frame instead of using some callback.

What you are using the function for isn't actually animation as far as I can tell, which the function is meant for.

**Comment by anka-213** [comment]
**More details:**
This code determines which framerate rAF uses:

    (function(){var a = 0;var af = function(){window.requestAnimationFrame(af);a +=1;};af();window.setTimeout(function(){af = function(){console.log(a)};},1000)})()

On Firefox it reports 60FPS as expected. But on Google Chrome on Win10 it reports 2000FPS, so it doesn't seem to limit the framerate at all.

**Comment by imsky** [comment]
Good catch - I'll look into using that snippet and throttling rAF calls if necessary.

**Comment by imsky** [comment]
This should be addressed on the latest build, let me know if you still see 100% CPU usage.

**Comment by anka-213** [comment]
Yes, it seems to be fixed. Thanks!

**Comment by imsky** [comment]
Great to hear, thank you for reporting this.

**Comment by DenerKup** [comment]
For me it still drains battery too fast. I have two tabs opened with holder.js and they consume about 10% of CPU. Notebook is heating. Chromium profiler shows most times goes to setTimeout and requestAnimationFrame.

The point I can't understand where animation is done? Placeholders are static.

**Comment by imsky** [comment]
if there are any fluid or auto-sized placeholders, then there will be a loop running for the whole page.

do you have an example page?
