### ISSUE TITLE
Transparent Image

### ISSUE THREAD

**Issue by aaronhb** [imsky/holder#151]
Is there a way to make it generate transparent images? I am looking for a responsive solution when using background images on a div with s specific aspect ration and cover. I have tried the css proportional div approach but it is not as reliable as using an image to maintain aspect on all screen sizes.

Any help is greatly appreciated. :)

**Comment by imsky** [comment]
Transparency will be added either in 2.9 or 3.0. Thanks for bringing this up.

**Comment by aaronhb** [comment]
AWESOME! and you knew this next question was coming...How long till you release it? :)

**Comment by imsky** [comment]
It's difficult to predict releases, but if it's going into 2.9, probably in August.

**Comment by aaronhb** [comment]
Awesome and thanks so much for all the hard work and effort you have put into this. Very cool!

**Comment by imsky** [comment]
Thanks, I appreciate that. I'll keep this issue open until the feature is implemented.

**Comment by imsky** [comment]
this is now implemented. you can set foreground or background to an rgba color, so a transparent placeholder can be created like this: `holder.js/300x200?bg=rgba(0,0,0,0.0)`

**Comment by lauraliism** [comment]
Hi, I am having some trouble with using Holder.js. I need a placeholder with transparent background, but this line `holder.js/300x200?bg=rgba(0,0,0,0.0)` doesn't really work.

**Comment by cliveb** [comment]
> Hi, I am having some trouble with using Holder.js. I need a placeholder with transparent background, but this line `holder.js/300x200?bg=rgba(0,0,0,0.0)` doesn't really work.

Does a working example help? https://github.com/cliveb/shiny-octo-telegram

**Comment by imsky** [comment]
@lauraliism seems like a bug - what happens is automatic foreground color setting fails and the whole image breaks. setting the foreground color works: http://jsfiddle.net/a08z6qvc/1/

`<img data-src="holder.js/300x200?bg=rgba(0,0,0,0.0)&fg=#ffffff">`
