### ISSUE TITLE
Holder won't import into a webpack project

### ISSUE THREAD

**Issue by at0g** [imsky/holder#162]
Hello,

Holder is installed with npm and I have been trying to import it into a webpack project with no good results.

I've tried using `exports-loader` (`exports?Holder!holderjs`) but it does not return Holder.

I've also tried aliasing to `holderjs/src`, but that fails to build due to missing dependencies (`trim` and `component-type`) in `src/lib/vendor/querystring.js`

Any suggestions?

**Comment by imsky** [comment]
Let me know if it still fails for you.

**Comment by at0g** [comment]
It's all good, my mistake. Sorry for the false bug report.
