### ISSUE TITLE
Some bg color values don't work without specifying fg color

### ISSUE THREAD

**Issue by Trapets** [imsky/holder#163]
Hei!

I noticed that some color values brake the holder.js. For example, without adding fg color value to the code below breaks Holder:
`<img src="holder.js/300x300?auto=yes&bg=00AEEF&text=Add image">`
and
`<img src="holder.js/300x300?auto=yes&bg=00AEEF&fg=000&text=Add image">`
works fine.

Trapets

**Comment by imsky** [comment]
interesting, i'll check it out

**Comment by imsky** [comment]
i can't replicate the breaking case - i see a blue placeholder as in the attached screenshot
what browser and what version of Holder are you using?

![holder](https://cloud.githubusercontent.com/assets/330895/10684160/1453ee5e-7918-11e5-9461-d712de095294.png)

**Comment by Trapets** [comment]
I use Holder.js ver.2.8.0+7srgw, machine runs Win 7 Pro, browsers Firefox 41.0.2 and Chrome 46.0.2490.80. 
![html_output](https://cloud.githubusercontent.com/assets/5584236/10703206/14cfa1a6-79d7-11e5-9114-55a44d09efe8.png)

**Comment by Trapets** [comment]
If i use this color value for only fg color, it works. If i use this color value for bg color, it breaks.
I'm not code wise. But i see some error log in my LightTable console, maybe it helps:

Uncaught TypeError: Cannot read property 'toString' of undefined
holder.js [2413] Color.toHex

**Comment by imsky** [comment]
2.8.0 unfortunately went out a bit too soon. can you try with 2.8.2 or 2.9.0?

**Comment by Trapets** [comment]
With 2.9.0 it works. Didn't test with 2.8.2.

**Comment by imsky** [comment]
ok, since this is fixed in a later release i'm closing the issue. please let me know if you see this bug again
