### ISSUE TITLE
License manifest missing

### ISSUE THREAD

**Issue by ilmente** [imsky/holder#172]
Hi @imsky,
my congratulations for the beautiful work!

I'd like to ask you if it's possible to add the MIT manifest inside the repo. 
I'm creating a commercial product that uses your work. MIT is declared both in readme and package.json, but from a formal legal prospective I'd need to have a LICENSE file with the copyright holder (you) placed inside the module (I'm using npm).

Can you do it? 
Thanks.

Best.
Alessandro

**Comment by imsky** [comment]
sure thing, will add

**Comment by ilmente** [comment]
Just created a PR. Ignore it if you prefer to proceed your way.
Thanks a lot.
