### ISSUE TITLE
update shaven dep to 0.8.1 (^0.8.1)

### ISSUE THREAD

**Issue by ilmente** [imsky/holder#174]
Hi, me again.

As already said:
> I'm creating a commercial product that uses your work. ...

And I asked shaven module creator to update it's component to a new fixed version (from legal prospective). Can I ask you, if possible, to update your `npm package.json` (and the registry) with the last version (0.8.1)?

Node Semver has a different behaviour depending on the major:
- `^0.7.3` > `0.7.x` with x >= 3;
- `^1.1.2` > `1.x.y` with x >= 1 and y >= 2; 

With major 0, it takes only patches as compatible; with major >= 1, it takes minor and patches as compatible. That prevents me to use legally updated version of `shaven` because your requirement is  `^0.7.3`.

Let me know if you can do it. Thanks.

**Comment by imsky** [comment]
makes sense, i'll merge the PR. hopefully nothing breaks :)

**Comment by abelspry** [comment]
Sorry for bothering you again: can you update the `npm` registry as well?
Obviously, whenever you're ready to do it.
Thanks.

**Comment by ilmente** [comment]
Great!
Sorry for bothering you again: can you update the npm registry as well?
Obviously, whenever you're ready to do it.
Thanks.

**Comment by imsky** [comment]
will do
