### ISSUE TITLE
React wrapper

### ISSUE THREAD

**Issue by Moeriki** [imsky/holder#179]
I created a React wrapper: [react-holder](https://github.com/Moeriki/react-holder).

If there is interest it could be included, or referenced.

As a side-question. Has there ever been discussions on server-side rendering? Looking at [jsdom](https://github.com/tmpvar/jsdom) mainly.

**Comment by imsky** [comment]
server-side rendering has definitely been on my mind - something to use in build processes for example. i'll be looking at it for 3.0.

thanks for the wrapper - it does kind of go around the idea of the URL being the config - i'll see if it can be adapted natively, and if not, i'll reference it in docs
