### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by wahoo189** [imsky/holder#186]
I am linking to Holder.js using an HTTPS link but am receiving the js via non-secure HTTP and that is causing an error on my (HTTPS) site. 

here is the link I am using:
`<script type='text/javascript' src="https://imsky.github.io/holder/holder.js"></script>`

and I am being redirected to:
http://holderjs.com/holder.js <-- not HTTPS.

am I using a bad link? the link itself specifies HTTPS.

**Comment by imsky** [comment]
first time i'm seeing this, not sure why Github is redirecting. will look into setting up HTTPS on holderjs.com

in the meantime please use the library from https://cdnjs.com/libraries/holder or http://www.jsdelivr.com/projects/holder

**Comment by wahoo189** [comment]
thanks for the updated link, it works and I am unblocked.

**Comment by imsky** [comment]
great to hear :+1:
