### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by riwakawebsitedesigns** [imsky/holder#191]
When adding 

```
<script type="text/javascript">
$( document ).ready(function() {
// For holder body image
Holder.addImage("holder.js/100px380?theme=social", "body").run();
});
</script>
```

It adds it to the body in the wrong position should be at top of page

![holder](https://cloud.githubusercontent.com/assets/5113934/16706306/8b4dd5dc-45fb-11e6-82d4-759885b5d8c8.png)

Is there any way to add it into a css link instead like below which I have tried but background image link not working.

```
body {
	padding-top: 64px;
	background-color: #E7E7E7;
	background-image: url("holder.js/100px380");
}
```

I have tried this but no luck the path is correct

`<body style="background: url(<?php echo base_url('assets/catalog/javascript/?holder.js/100x380?theme=simple');?>);">
`
It echos out

`<body style="background: url(http://localhost/codeigniter/assets/catalog/javascript/?holder.js/100x380?theme=simple);">`

**Comment by imsky** [comment]
`addImage` appends the placeholder: https://github.com/imsky/holder/blob/v2.9.3/src/lib/index.js#L55

you can do one of several things:

* use a `<img>` tag
* add a blocking `<script>` tag (no `$(document).on('ready')`) immediately after opening `<body>`
* add a containing `<div>` immediately after opening `<body>` and use it with `addImage`
