### ISSUE TITLE
Support for RGBA without leading zero

### ISSUE THREAD

**Issue by LarryAzevedo** [imsky/holder#205]
It would be great if we could get support for RGBA.  For example:
```
Holder.addTheme("custom", {
   bg: rgba(13, 97, 145, .1),
   fg: rgba(63, 127, 185, .4)
});
```
and
```
<img data-src="holder.js/300x200?bg=rgba(13, 97, 145, .1)&amp;fg=rgba(63, 127, 185, .4)">
```

Thoughts?

**Comment by imsky** [comment]
fairly sure this is implemented: https://github.com/imsky/holder/blob/master/test/index.html#L52

let me know if it doesn't work for you

**Comment by LarryAzevedo** [comment]
Ok so here's the issue. It only works if you have a leading zero in the alpha channel.  So it doesn't work with: `bg=rgba(13, 97, 145, .1)` but does work with `bg=rgba(13, 97, 145, 0.1)`.

**Comment by imsky** [comment]
hmm i guess that's annoying. i'll update the issue to fix that

**Comment by LarryAzevedo** [comment]
Great!  Thank you very much.
