### ISSUE TITLE
(angular) binding to data-src

### ISSUE THREAD

**Issue by pliablepixels** [imsky/holder#211]
Hi, I know this is not directly related to your excellent plugin - it refers to the angular wrapper that you refer to in your readme. Unfortunately, I am not sure if the author of that wrapper is active.

So I'm posting here incase someone uses this in angular and knows how to resolve how one can bind `[data-src]` to a variable? (I posted the original issue here https://github.com/aogriffiths/angular-2-holderjs/issues/2)

**Comment by pliablepixels** [comment]
problem solved, moving the code to ngInit worked

**Comment by pliablepixels** [comment]
sorry, too hasty - problem still persists - ideas welcome :)

**Comment by imsky** [comment]
hmm good question. i'm planning better integration for libraries like Angular, React, etc. for Holder 3

since i don't use Angular 2, i don't have an immediate answer for you, but i could investigate if you post a fiddle that can reproduce your issue (which seems to be placeholders not working with Angular 2).

**Comment by pliablepixels** [comment]
Hi @imsky,
The problem is that using either data-binding or expression evaluation does not work in angular. Using a static text value does work

I've set up an example:

https://plnkr.co/edit/ibOyJvmNWadQWOm6Ki7u?p=info

(The code is in `home.page.ts/html`)

thanks!

**Comment by pliablepixels** [comment]
Hi, this problem was resolved. I forked and created a version that works
https://github.com/pliablepixels/angular-2-holderjs

The problem was resolved by this post: https://stackoverflow.com/a/46673111/1361529
