### ISSUE TITLE
[Enhancement] Diagonal lines/border?

### ISSUE THREAD

**Issue by Quix0r** [imsky/holder#213]
Is it possible to render diagonal lines and a border? I mean something like this:

http://dhiglobal.com/wp-content/uploads/2016/07/placeholder.jpg

Here, the border is missing, maybe a new config `border = true/false` (default: `false`) and `diagonals = true/false` (default: `false`)?

**Comment by imsky** [comment]
this already exists, use `outline=1`, e.g. `<img data-src="holder.js/300x200?outline=1">`

example: https://jsfiddle.net/m28ntzou/

![screen shot 2017-10-23 at 11 09 42 am](https://user-images.githubusercontent.com/330895/31896817-affba85a-b7e2-11e7-9589-ddacfa9b4287.png)

**Comment by Quix0r** [comment]
Ops, maybe I missed it?

**Comment by imsky** [comment]
sure thing @Quix0r

**Comment by Quix0r** [comment]
Hmm, if I use `border-size: xFOO` like `5px`, the border is not rendered on the rounded border corners. Maybe a general issue with CSS?

**Comment by imsky** [comment]
@Quix0r i'm not 100% sure what you mean. can you post a jsfiddle with the issue?

**Comment by Quix0r** [comment]
Again signing up somewhere ... :-/ I have uploaded a screenshot to my nextcloud instance:
https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY?path=%2Fholderjs#/holderjs/20171102%20-%20Rounded%20Corner%20-%20001.png

**Comment by imsky** [comment]
you can use jsfiddle without signing up @Quix0r 

good point about the rounded corners - that wasn't factored into the "outline" feature. i'll file an issue to support this.

**Comment by Quix0r** [comment]
Maybe I looked too fast. Anyway. Thank you for supporting this.
