### ISSUE TITLE
How to make images scaled down?

### ISSUE THREAD

**Issue by miriam-z** [imsky/holder#215]
Can't seem to find image scaling down?
part of my React component:
Changing the 25x25? to other values does not seem to have any affect?

    return (
            <div>
                <ul>
                    {arrays.map(array =>
                        <li key={array.id}>
                            <div><img src={array.author.avatarUrl} alt="" className="img-thumbnail"
                                      data-src="holder.js/**25x25**?auto=yes" id="new"/></div>
                            <div>{array.title} {array.tags}</div>
                            <div>Created on {array.timestamp} by {array.author.username}</div>
                            <div>{array.body}</div>
                        </li>)}
                </ul>
            </div>

**Comment by imsky** [comment]
could you please create a jsfiddle/codepen or another way to reproduce this issue?

a screenshot would also be a good start to understanding what the problem is.
