### ISSUE TITLE
holder.js does not work when the page renders twice in React

### ISSUE THREAD

**Issue by cindy100295** [imsky/holder#225]
I am using holder.js in React with react-bootstrap. In `index.html` I added in `<header>`: 
`<script src="holder.js"></script>`

In the component `ProjectCard` I wrote: 
`<Card.Img className="proj-card-img" variant="top" data-src="holder.js/100px180" />`

This component is rendered using map() function
```
{Object.keys(this.state.projects).map(key=>
     <ProjectCard key={key} index={key} details={this.state.projects[key]}/>)}
```

It works nicely if I set state in `ComponentWillMount()`. However, if I update the state and the page renders twice (e.g. use firebase to syncState), holder.js will not work. 

I have tried 
```
<script>
    Holder.run({
        images:"MyClassName"
    })
</script>
```
but it didn't work either. 

Did I write anything wrong? Thanks!

**Comment by imsky** [comment]
@cindy100295 could you provide a fiddle or a Gist (or anything that works for you) of the page?

in the meantime, i think one thing you could try is change this:

```js
Holder.run({
        images:"MyClassName"
    })
```

to this:

```js
Holder.run({
        images:".MyClassName" // should be .proj-card-img if going by your comments
    })
```

note the . before the class name, as the `images` property needs to be a valid CSS selector

**Comment by cindy100295** [comment]
My code in index.html: 
```
<head>
  <script src="holder.js"></script>
  <script>
      Holder.run({
        images: '.proj-card-img'
      })
    </script>
</head>
```

In React Component: 

`<Card.Img className="proj-card-img" variant="top" data-src="holder.js/100px180" />`

But this time it does not show anything.  

Some background: I have five cards, two of them are loaded from a JSON file (local). Three of them I pulled from Firebase (remote). Every time the two local cards render first. Then the other three show up later. Holder.js work for the local two but not for the remote three. 

If I wrote the code above, five cards have no placeholder images. 
Maybe it is because when the component updates, `index.html` does not refresh? Or my code is wrong...

**Comment by imsky** [comment]
could you try something like this instead:

```js
componentDidMount: function () {
  requestAnimationFrame(function () {
    Holder.run({
      images: '.proj-card-img'
    });
  });
}
```

also, as a followup, you could try passing a Node (Element) to `images` which works better if you treat each placeholder as a component

**Comment by cindy100295** [comment]
Thanks! I figure it out. 
In index.html: 
```
<script>
    function holder() {
      Holder.run({
        images: ". MyClassName"
      })
    }
</script>
```
In component: 
```
componentDidMount() {
    window.holder();
```
And then it works.

**Comment by imsky** [comment]
nice @cindy100295 i'll look into adding this to docs

**Comment by Senninseyi** [comment]
i used mine without the didmountComponent.... like this
`import 'holderjs'
{
                img: "holder.js/100px270",
                textHeader: "Well handled customers",
                link: "Our reviews on Reviews.co.uk",
            },
`
where it is being used

**Comment by nimbus2300** [comment]
I struggled to get holderjs 2.9.7 (https://www.npmjs.com/package/holderjs) working nicely in react bootstrap 1.4 (bootstrap 4.5.3).

I was trying to use it in a class component. In the end this worked:

`yarn add holderjs && yarn install`

Then in my component:

```
import { run as runHolder } from 'holderjs/holder';

class Foobar extends Component

 constructor(props) {
    ...
    this.runHolder = runHolder;
  }

 componentDidMount() {
   this.runHolder('image-class-name-no-initial-dot');
}

```
And on the image:

`<Image src="holder.js/100x100"/>`

**Comment by imsky** [comment]
cool @nimbus2300 - glad you got it working. will keep that in mind when there's a native react component

**Comment by sersart** [comment]
Hi,
you can run holderjs in React function without any problem. Please check example.

```
import React, { Fragment, useEffect } from "react";
import { Image } from "react-bootstrap";
import { run as runHolder } from 'holderjs/holder';

export function HolderExample() {
    useEffect(() => {        
        runHolder('image-class-name');
    });
    return (
         <Fragment>
           <Image 
                  className="image-class-name"
                  roundedCircle
                  src="holder.js/20x20?text=J&bg=28a745&fg=FFF"
            /> 
          </Fragment>
    );

```


Have fun.

**Comment by arnil6585** [comment]
yoieh:patch-1

**Comment by albertorodriguezdiaz** [comment]
Hi All.
You need to add:
1) 
`import { run as runHolder } from 'holderjs/holder';`
2)
`useEffect(() => {        
        runHolder('image-class-name');
    });`
It's all 😃 
![imagen](https://user-images.githubusercontent.com/27173859/143277574-98796d5d-bbef-4d9a-ba17-43c63ea413f2.png)

**Comment by nimbus2300** [comment]
> Hi All. You need to add: 1) `import { run as runHolder } from 'holderjs/holder';` 2) `useEffect(() => { runHolder('image-class-name'); });` It's all 😃 ![imagen](https://user-images.githubusercontent.com/27173859/143277574-98796d5d-bbef-4d9a-ba17-43c63ea413f2.png)

Assuming you're working with functional components, yes.

**Comment by gunslingor** [comment]
It only seems to work when I go to a URL, but when I use the react router to change the content of div for example with a navbar, it doesn't load.


```
import Container from "react-bootstrap/Container";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'holderjs/holder';

class ProductList extends React.Component {
    render() {
        return (
            <Container>
                <Row xs={1} md={2} className="g-4">
                    <Col>
                        <Card>
                            <Card.Img variant="top" src="holder.js/100px160" />
                            <Card.Body>
                                <Card.Title>Card title</Card.Title>
                                <Card.Text>
                                    This is a longer card with supporting text below as a natural
                                    lead-in to additional content. This content is a little bit
                                    longer.asdfff
                                </Card.Text>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>
        );
    }
}
class Routing extends React.Component {
    render() {
        return (
        <BrowserRouter>
            <Routes>
                <Route path="/" element={ <Layout /> }>
                    <Route path="Home" element={ <Home /> } />
                    <Route path="Shop" element={ <Shop /> } />
                    <Route path="About" element={ <About /> } />
                    <Route path="Contact" element={ <Contact /> } />
                </Route>
                <Route path="*" element={<Navigate to="/Home" />} />
            </Routes>
        </BrowserRouter>
        )
    }
}
```

**Comment by gunslingor** [comment]
@nimbus2300 Thanks that solve it for me eventually. I think I understand it too, learning... was confused by runHolder... it's really run holder.js not a holder of run operations, lol, was confused. One thing I can't understand and google can't find is how this image-class-name-no-initial-dot class or 'userOptions' argument works.

**Comment by meiyingqishi** [comment]
Hello, @imsky, I've written a test project using `next.js + pnpm + typescript + react-bootstrap + holdderjs`. I've encountered the following error:
```
⨯ node_modules/holderjs/holder.js (13:14) @ document
⨯ TypeError: Cannot read properties of undefined (reading 'document')
    at __webpack_require__ (/Users/myqs/Downloads/bootstrap-react-demo/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:33:73)
    at (ssr)/./src/app/page.tsx (/Users/myqs/Downloads/bootstrap-react-demo/.next/server/app/page.js:162:1)
    at __webpack_require__ (/Users/myqs/Downloads/bootstrap-react-demo/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
```

The test code is as follows:
```
'use client';

import { useEffect } from 'react';
import { Card } from 'react-bootstrap';
import { run as runHolder } from 'holderjs/holder';

export default function Home() {
  useEffect(() => {        
    runHolder('my-card-img');
  });

  return (
    <main>
      <Card style={{ width: '18rem' }}>
        <Card.Img className='my-card-img' variant='top' src="holder.js/100x180?text=Image cap" />
        <Card.Body>
          <Card.Title>Card Title</Card.Title>
          <Card.Text>
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </Card.Text>
        </Card.Body>
        <ListGroup className='list-group-flush'>
          <ListGroup.Item>Cras justo odio</ListGroup.Item>
          <ListGroup.Item>Dapibus ac facilisis in</ListGroup.Item>
          <ListGroup.Item>Vestibulum at eros</ListGroup.Item>
        </ListGroup>
        <Card.Body>
          <Card.Link href='#'>Card Link</Card.Link>
          <Card.Link href='#'>Another Link</Card.Link>
        </Card.Body>
      </Card>
    </main>
  );
}
```

Please take a look and help me out, thank you very much, I appreciate it.

**Comment by arvera** [comment]
I still can't get it to work. Where does the runHolder need to be? on the root component?, the parent component? or the component that has the holdjs?


And what if I already have a userEffect? I added it at the top of the already existing userEffect

**Comment by arvera** [comment]
It sees that if I have it at the child element, it just barks at me dunno why.  If I have it at the parent, it also barks at me. Both times with the same error: 

This is the child element: 
<img width="598" alt="Image" src="https://github.com/user-attachments/assets/743d6c58-0c70-445b-be66-fa9be6da1c39" />

This is the parent using the child element (only showing the part where the element gets used) but I do have the useEffect:
<img width="410" alt="Image" src="https://github.com/user-attachments/assets/436b2e27-958b-4eea-8d3a-15cba6a03ddf" />

I have tried them one on each place, but not at the sametime. 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'document')
    at exports2.newEl (holderjs_holder.js?v=f5df5c37:1613:29)
    at holderjs_holder.js?v=f5df5c37:3271:32
    at Object.<anonymous> (holderjs_holder.js?v=f5df5c37:3317:14)
    at __webpack_require__ (holderjs_holder.js?v=f5df5c37:218:31)
    at Object.<anonymous> (holderjs_holder.js?v=f5df5c37:245:38)
    at Object.<anonymous> (holderjs_holder.js?v=f5df5c37:1133:16)
    at __webpack_require__ (holderjs_holder.js?v=f5df5c37:218:31)
    at Object.<anonymous> (holderjs_holder.js?v=f5df5c37:230:31)
    at __webpack_require__ (holderjs_holder.js?v=f5df5c37:218:31)
    at holderjs_holder.js?v=f5df5c37:225:18
```
