### ISSUE TITLE
old dependency version prevent install with engine-strict=true

### ISSUE THREAD

**Issue by ValeryVS** [imsky/holder#232]
Can you upgrade shaven to `2.0.0`?
`0.8.1` contains `node: ~0.12.0` in `engines`.
It works on new nodejs versions, but can't be installed with `engine-strict=true`.

**Comment by ValeryVS** [comment]
@imsky Can you look at it?
Topic was raised in #209 previously, but now engine restriction was removed from shaven.

**Comment by imsky** [comment]
@ValeryVS the engine issue is now fixed in 2.9.9

**Comment by ValeryVS** [comment]
Thank you! It works with `engine-strict=true` now.
