### ISSUE TITLE
Maintain aspect ratio of fluid images?

### ISSUE THREAD

**Issue by Fatbat** [imsky/holder#63]
I may have missed something, but as it currently stands fluid images will shrink horizontally but always maintain the original height. I'd like the image to maintain its aspect ratio as it shrinks, so the height should decrease as the width decreases.

Is this possible?

**Comment by davcpas1234** [comment]
For anyone having this issue more recently, this is now implemented like so: <img data-src="holder.js/100px100?auto">.
